"""test migration

Revision ID: b09f0bfc18db
Revises: 
Create Date: 2023-04-21 21:02:01.515923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09f0bfc18db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usertype', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('messages', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shoppingCartCount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('profits', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('spending', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['password_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status')
        batch_op.drop_column('spending')
        batch_op.drop_column('profits')
        batch_op.drop_column('shoppingCartCount')
        batch_op.drop_column('messages')
        batch_op.drop_column('gender')
        batch_op.drop_column('date')
        batch_op.drop_column('description')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('usertype')
        batch_op.drop_column('admin')
        batch_op.drop_column('staff_id')
        batch_op.drop_column('retailer_id')

    # ### end Alembic commands ###
